"""Initial_migration

Revision ID: 6aa3a18e4724
Revises: 
Create Date: 2026-03-20 20:17:53.419539

"""

from alembic import op
import sqlalchemy as sa


revision = '6aa3a18e4724'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_type', sa.Text(), nullable=False),
    sa.Column('rule_value', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_market_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tradable', sa.Boolean(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('normalized_title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('outcomes_json', sa.JSON(), nullable=False),
    sa.Column('raw_payload_json', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('market_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_pairs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id_a', sa.Integer(), nullable=False),
    sa.Column('market_id_b', sa.Integer(), nullable=False),
    sa.Column('pair_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_reason_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id_a'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['market_id_b'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair_hash')
    )
    op.create_table('arb_opportunities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_pair_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('price_leg_1', sa.Float(), nullable=False),
    sa.Column('price_leg_2', sa.Float(), nullable=False),
    sa.Column('avg_price_leg_1', sa.Float(), nullable=False),
    sa.Column('avg_price_leg_2', sa.Float(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('capital_required', sa.Float(), nullable=False),
    sa.Column('gross_profit', sa.Float(), nullable=False),
    sa.Column('net_profit', sa.Float(), nullable=False),
    sa.Column('gross_roi', sa.Float(), nullable=False),
    sa.Column('net_roi', sa.Float(), nullable=False),
    sa.Column('calculation_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_pair_id'], ['market_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(), nullable=False),
    sa.Column('message_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['arb_opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('arb_opportunities')
    op.drop_table('market_pairs')
    op.drop_table('market_entities')
    op.drop_table('settings')
    op.drop_table('markets')
    op.drop_table('blacklist_rules')
    # ### end Alembic commands ###